### ISSUE TITLE
is nio connector absolutely necessary ?

### ISSUE THREAD

**Issue by snimavat** [kensiprell/grails-atmosphere-meteor#52]
If BuildConfig is not configured to use nio connector, plugin gives this error

``` Your BuildConfig.groovy must be configured to use the Servlet 3.0 API and the Tomcat NIO connector. ```

I am confused, is nio and servlet3 is really needed for underlying atmosphere plugin to work in both production and development environment, or this is needed for development environment only.

Because I deployed the war to tomcat7 without nio connector and web socket / long polling seem to work just fine. They why the plugin is forcing servlet3.0 and nio.

@kensiprell can you please clarify this.

**Comment by kensiprell** [comment]
NIO and 3.0 are requirements for Atmosphere Framework; however, the check should only run in a development environment: https://github.com/kensiprell/grails-atmosphere-meteor/blob/master/AtmosphereMeteorGrailsPlugin.groovy#L80-L82.

**Comment by snimavat** [comment]
@kensiprell Definitely it works without nio in production.

**Comment by kensiprell** [comment]
If it's working for you, great! Perhaps that only applied to early framework versions. In any case, the message can be ignored.
