### ISSUE TITLE
Error message - i don't know why am i getting this ?

### ISSUE THREAD

**Issue by rahulcse1** [kensiprell/grails-atmosphere-meteor#53]
| Enabling Tomcat NIO connector
logDirectory: C:\Users\amar\Desktop\tw\amar\logs

Configuring Spring Security Core ...
... finished configuring Spring Security Core

Configuring Spring Security Facebook ...
... finished configuring Spring Security Facebook

********************************************************************
* The atmosphere-meteor plugin requires the following settings in  *
* your grails-app/conf/BuildConfig.groovy:                       *
* grails.servlet.version = "3.0"                                   *
********************************************************************

I checked AtmosphereMeteorGrailsPlugin.groovy
servletContext.effectiveMajorVersion is coming 2
servletContext.majorVersion is coming 3

**Comment by rahulcse1** [comment]
i am also getting  below line in my log file.

ERROR conf.AtmosphereMeteorBootStrap$1  - AtmosphereFramework not found: atmosphereMeteor bean not initialized

**Comment by rahulcse1** [comment]
I checked AtmosphereMeteorGrailsPlugin.groovy
servletContext.effectiveMajorVersion is coming 2
servletContext.majorVersion is coming 3

**Comment by kensiprell** [comment]
If you upload the app to github, I'll take a look. Otherwise, what Grails and Atmosphere versions are you using? Also, seeing your BuildConfig.groovy would help.

It could be safe to ignore the error in your first comment, but the second one is a problem.

Ken

**Comment by rahulcse1** [comment]
Grails : 2.2.4
Atmosphere: 1.0.5

Below is my build config.
--------------------------------------

grails.servlet.version = "3.0"
grails.tomcat.nio = true
grails.project.class.dir = "target/classes"
grails.project.test.class.dir = "target/test-classes"
grails.project.test.reports.dir = "target/test-reports"

//grails.project.work.dir = 'target'

grails.project.target.level = 1.7
grails.project.source.level = 1.7
grails.project.war.file = "target/${appName}.war"

// uncomment (and adjust settings) to fork the JVM to isolate classpaths
//grails.project.fork = [
//   run: [maxMemory:1024, minMemory:64, debug:false, maxPerm:256]
//	run: [maxMemory: 1024, minMemory: 256, debug: false, maxPerm: 256], // configure settings for the run-app JVM
//	war: [maxMemory: 1024, minMemory: 256, debug: false, maxPerm: 256], // configure settings for the run-war JVM
//	console: [maxMemory: 768, minMemory: 64, debug: false, maxPerm: 256]// configure settings for the Console UI JVM
//]

if (System.getProperty("grails.debug")) {
	grails.project.fork.war += [debug: true]
	grails.project.fork.run += [debug: true]
	println "Using debug for run-war"
 }
grails.project.dependency.resolver = "maven"
grails.project.dependency.resolution = {
    // inherit Grails' default dependencies
    inherits("global") {
        // specify dependency exclusions here; for example, uncomment this to disable ehcache:
        // excludes 'ehcache'
    }
    log "error" // log level of Ivy resolver, either 'error', 'warn', 'info', 'debug' or 'verbose'
    checksums true // Whether to verify checksums on resolve
    legacyResolve false // whether to do a secondary resolve on plugin installation, not advised and here for backwards compatibility

    repositories {
        inherits true // Whether to inherit repository definitions from plugins

        grailsPlugins()
        grailsHome()
        grailsCentral()

        mavenLocal()
        mavenCentral()
		
        // uncomment these (or add new ones) to enable remote dependency resolution from public Maven repositories
        mavenRepo "http://snapshots.repository.codehaus.org"
        mavenRepo "http://repository.codehaus.org"
        mavenRepo "http://download.java.net/maven/2/"
        mavenRepo "http://repository.jboss.com/maven2/"
		
		// uncomment below stuff if facing dependency resolved issue.
		mavenRepo "http://repo.grails.org/grails/repo/"
		mavenRepo "http://oss.sonatype.org/content/repositories/snapshots"
    }

    dependencies {
		runtime 'mysql:mysql-connector-java:5.1.28'
		compile 'log4j:apache-log4j-extras:1.1'
		compile 'org.springframework.social:spring-social-core:1.0.1.RELEASE'
		compile 'org.springframework.social:spring-social-facebook:1.0.1.RELEASE'
    }

    plugins {
        runtime ":hibernate:$grailsVersion"
        runtime ":resources:1.2"
	runtime ":jquery:1.10.2"
        build   ":tomcat:$grailsVersion"
        runtime ":database-migration:1.3.2"
		compile ':cache:1.0.1'
		compile ":platform-core:1.0.0"
		runtime ":quartz:1.0.2"
		compile ":mail:1.0.7"
		compile ":atmosphere-meteor:1.0.5"
		compile ":searchable:0.6.4"
		compile ":oauth:2.6.1"
		compile ":spring-security-core:1.2.7.3"
		compile ":spring-security-facebook:0.15.4"
    }
}

**Comment by kensiprell** [comment]
I'd overlooked that ```servletContext.effectiveMajorVersion``` = 2 in your first post. This is definitely a problem. Is this happening with ```grails run-app``` or deploying a WAR to a Tomcat server? If it's development mode, I'm still puzzled:

* ```build   ":tomcat:$grailsVersion"``` should use Tomcat 7.0.42, which is not a problem.

* ```grails.servlet.version = "3.0"``` should force Tomcat to use the 3.0 API.

I haven't forgotten about your email message. I just haven't had time to research it.

**Comment by rahulcse1** [comment]
I am getting this one with grails run-app.
I did not deployed war, i'll check that one today. thanks

**Comment by kensiprell** [comment]
I would not expect that problem with run-app, which should force the embedded server to use 3.0.

**Comment by rahulcse1** [comment]
I figure out the problem was it was not updating web.xml.
So I manually change to servlet 3.0.

No it's working fine.

**Comment by kensiprell** [comment]
Good news!

**Comment by rahulcse1** [comment]
thanks for help :)
