### ISSUE TITLE
Grails 3.0.x Support

### ISSUE THREAD

**Issue by jojopad** [kensiprell/grails-atmosphere-meteor#54]
It would be great if grails-atmosphere-meteor plugin will be upgraded to support Grails 3.0.x.

**Comment by kensiprell** [comment]
I did some [experimenting](https://github.com/kensiprell/grails3-atmosphere-sample) with Grail 3 without a plugin, but I don't think it's worth the effort. I especially had trouble with dependency injection.

I recommend the [spring-websocket plugin](https://github.com/zyro23/grails-spring-websocket), which is what I intend to use with Grails 3.
