### ISSUE TITLE
Questions about generated *MeteorHandler & *MeteorServlet

### ISSUE THREAD

**Issue by rgoldberg** [kensiprell/grails-atmosphere-meteor#55]
I have a few questions about the generated `*MeteorHandler` & `*MeteorServlet` code?  (the readme mentioned using issues for questions, so...)

What is the point of the generated `*MeteorHandler`?

Is there any reason why I shouldn't just add my own `AtmosphereHandler` implementation to the `AtmosphereFramework` from `framework()` in the generated `*MeteorServlet`?

What is the point of building a `Meteor` in the `doGet` of the generated `*MeteorHandler`, and of broadcasting only the first line of the body of the request in `doPost` of that class?

Why are the classes located under `grails-app/atmosphere`?  Can I just put them under `src`?  Can they be Java instead of Groovy?

I'm trying to upgrade Atmosphere from 2.2.x to 2.3.5 in an existing grails app, and from the ancient atmosphere Grails plugin to atmosphere-meteor, but the atmosphere / meteor documentation is byzantine, and doesn't really seem to indicate why such complexity is useful.

The application already has an existing `AtmosphereHandler` implementation that has a non-trivial `onStateChange` & `onRequest`, the latter of which handles both GET & PUT.  Is the "correct" idea to create a `Meteor` in both `doGet` & `doPut`, and then move the code from the existing `AtmosphereHandler#onRequest` for GET & PUT into `doGet` & `doPut`, respectively, using the `AtmosphereResource` returned from `Meteor#getAtmosphereResource()` instead of the argument to the old `onRequest`?

What do I do about the existing `onStateChange`?

Thanks for any help.

**Comment by kensiprell** [comment]
I’ll try and answer your questions; however, first a general comment. As I’m sure you are aware, plugins are always a tradeoff. In other words, the plugin author has to make some decisions about how to implement functionality without constraining a plugin user. The usual compromise is that some things have to be done a certain way. So, if I don’t address a specific question, it probably falls in this category.

The ```*MeteorHandler``` classes allow you to customize endpoint handling, i.e. what to do when a client connects to a specific URL. For example, you might want to do some authorization checks, make some database modifications, etc.

See this [link](https://github.com/Atmosphere/atmosphere/wiki/Getting-Started-with-Meteor,-WebSocket-and-Long-Polling) for answers on ```MeteorServlet```, including “building” a ```Meteor```. The Meteor API will not be available in Atmosphere 3.0, so if you want to use Grails and be future-proof, you should consider Grails 3 and the [spring-websocket plugin](https://github.com/zyro23/grails-spring-websocket).

You can broadcast whatever you want in a ```doPost``` method and not just the first line of the request body. I suspect you are referring to a method that is simply echoing something back to the client. 

Using Java classes should work, but I haven’t tried that.

You only need to create the ```Meteor``` in the ```doGet``` method of a handler.

You should read [this tutorial]( http://async-io.org/tutorial.html), keeping in mind that the Meteor API is simply a wrapper for ```AtmosphereHandler```. The plugin’s [sample app]( https://github.com/kensiprell/grails-atmosphere-meteor-sample) will also be useful for seeing how it all works together. I don’t remember what an ```onStateChange``` method looks like, but newer versions of ```AtmosphereFramework``` should handle that type of work automatically.

If I've overlooked something or you still have questions, let me know.

**Comment by rgoldberg** [comment]
Thanks for all the info, and for having written the plugin.

The echo of the first line of the request body was just what this plugin generates for the `*MeteorHandler#doPost(...)` method, but it wasn't commented as being just an example method body, but it sounds like you've verified that it is just an example.

It sounds like I can just use my existing `AtmosphereHandler` in the generated `*MeteorServlet` instead of the `ReflectorServletProcessor` for the generated `*MeteorHandler` (the latter of which I can just delete).  Please let me know if I'm wrong.

It looks like you might use the `grails-app/atmosphere` directory for the generated servlets so you can watch the files for changes; the plugin currently only watches for changes for groovy files, not java files, so if I want to watch for changes, I can't use java.  I assume that if I don't want to watch for changes in the source, then I can use java, and/or move the generated source to a different directory, like `src/main/java`.  Please let me know if I'm wrong.

I can't move to Grails 3 yet, and it sounds like the spring-websocket plugin is only available for Grails 3+.

How would I obtain a `BroadcasterFactory` and `AtmosphereFramework` when using the spring-websocket plugin?  An injected `AtmosphereMeteor` provides access to both of those, but, if I switched from the atmosphere-meteor plugin to spring-websocket, `AtmosphereMeteor` wouldn't be available to me anymore.

**Comment by kensiprell** [comment]
Yes, it's just an example.

I don't know if dropping  ```ReflectorServletProcessor ``` will work. I'd stick with what's known to work, but of course, if it works, use it.

Not reloading the classes when they change would be a real pain during development. I should have used an asterisk instead of "groovy" in the ```watchedResources ``` closure. You could clone the repo, change the closure and version, and install the plugin to your local maven repo, and use it from there.

The spring-websocket plugin will work with versions < 3.0, but I believe you lose some functionality. Spring websocket does not use the Atmosphere Framework, so it would require a complete rewrite of your backend and client-side code.. See this [tutorial](https://spring.io/guides/gs/messaging-stomp-websocket/) for an introduction.
