### ISSUE TITLE
How do I get an instance of AtmosphereResourceFactory?

### ISSUE THREAD

**Issue by confile** [kensiprell/grails-atmosphere-meteor#56]
How do I get an instance of ``org.atmosphere.cpr.AtmosphereResourceFactory``?

**Comment by kensiprell** [comment]
This should work. Inject the [AtmosphereMeteor bean](https://github.com/kensiprell/grails-atmosphere-meteor#atmospheremeteor-bean) and use it.

    def atmosphereMeteor
    def atmosphereResourceFactory = atmosphereMeteor.framework.AtmosphereResourceFactory

If this doesn't work, reopen the issue.

Ken

**Comment by confile** [comment]
thanks
