### ISSUE TITLE
Using native Websockets with Tomcat8

### ISSUE THREAD

**Issue by confile** [kensiprell/grails-atmosphere-meteor#57]
I want to use Atmosphere with native websockets, because I guess they are much faster. 

here is my BuildConfig: 

```
grails.project.dependency.resolution = {
   inherits("global") {
      excludes "atmosphere-runtime" // must be excluded when using atmosphere-runtime-native
      excludes "atmosphere-compat-tomcat7"   

    }
...

dependencies {
   compile 'org.atmosphere:atmosphere-runtime-native:2.4.1.4'
  ....
}
}
```

My ``web.xml`` contains:

```
	<listener>
   		<listener-class>org.atmosphere.cpr.SessionSupport</listener-class>
	</listener>
	
	<servlet>
		<description>AtmosphereServlet</description>
		<servlet-name>AtmosphereServlet</servlet-name>
		<servlet-class>test.AtmosphereServlet</servlet-class>
		<load-on-startup>0</load-on-startup>

<async-supported>true</async-supported>

		<init-param>
			<param-name>org.atmosphere.cpr.AtmosphereInterceptor</param-name>
			<param-value>org.atmosphere.interceptor.AtmosphereResourceLifecycleInterceptor,org.atmosphere.interceptor.HeartbeatInterceptor</param-value>			
</init-param>

		<init-param>
		       <param-name>org.atmosphere.useWebSocketAndServlet3</param-name>
		       <param-value>false</param-value>
		</init-param>

      <init-param>
          <param-name>org.atmosphere.useNative</param-name>
          <param-value>true</param-value>
      </init-param>

		<init-param>
			<param-name>org.atmosphere.cpr.sessionSupport</param-name>
			<param-value>true</param-value>
		</init-param>

		<init-param>
			<param-name>org.atmosphere.cpr.broadcasterCacheClass</param-name>
 			<param-value>org.atmosphere.cache.UUIDBroadcasterCache</param-value>
		</init-param>
	</servlet>
	<servlet-mapping>
		<servlet-name>AtmosphereServlet</servlet-name>
		<url-pattern>/socket/*</url-pattern>
	</servlet-mapping>

```

When I try to use websockets I get the following error in my chrome console: 

```
WebSocket connection to 'ws://confile.no-ip.biz:8080/majestella/socket/app/234324?X-Atmosphere-tracking-id=0&X-Atmosphere-Framework=2.3.1-javascript&X-Atmosphere-Transport=websocket&Content-Type=application/json;%20charset=UTF-8&X-atmo-protocol=true' failed: Error during WebSocket handshake: Unexpected response code: 200
atmosphere.js:3251 Websocket closed, reason: Connection was closed abnormally (that is, with no close frame being sent). - wasClean: false
```

Did I miss something?

**Comment by kensiprell** [comment]
I'm not sure I can help with this. I originally tried to make the plugin agnostic to the runtime and native libraries, but I had so many problems with native that I gave up. However, I'll give it a shot.

- I know this is basic, but that 200 return code leads me to think you don't have anything on the server side to handle the endpoint (/socket/app/234324). Are you using the [```ReflectorServletProcessor```](https://github.com/kensiprell/grails-atmosphere-meteor-sample/blob/master/grails-app/atmosphere/org/grails/plugins/atmosphere_meteor_sample/DefaultMeteorServlet.groovy) along with a [handler](https://github.com/kensiprell/grails-atmosphere-meteor-sample/blob/master/grails-app/atmosphere/org/grails/plugins/atmosphere_meteor_sample/ChatMeteorHandler.groovy)?

- Have you tried getting the app working using ```atmosphere-runtime``` and the plugin and then converting it to ```atmosphere-runtime-native```?

I know the atmosphere docs are difficult to wade through, but you might want to check them out. It seems like I remember seeing a gotcha page for native support.

I'm planning on using Grails 3 and [grails-spring-websocket](https://github.com/zyro23/grails-spring-websocket) in all my future projects, so if that's an option for you, I strongly advise that route.

Ken

**Comment by confile** [comment]
thanks
