### ISSUE TITLE
Could not use PoolableBroadcasterFactory

### ISSUE THREAD

**Issue by confile** [kensiprell/grails-atmosphere-meteor#59]
Have you been able to use PoolableBroadcasterFactory as suggested here: 

https://github.com/Atmosphere/atmosphere/wiki/Improving-Performance-by-using-the-PoolableBroadcasterFactory

**Comment by kensiprell** [comment]
No, I haven't tried that. However, after looking at the wiki page, it might be possible with some changes in [the plugin config](https://github.com/kensiprell/grails-atmosphere-meteor-sample/blob/master/grails-app/conf/AtmosphereMeteorConfig.groovy) and [a handler](https://github.com/kensiprell/grails-atmosphere-meteor-sample/blob/master/grails-app/atmosphere/org/grails/plugins/atmosphere_meteor_sample/ChatMeteorHandler.groovy).

If you get it to work, please post a short how-to here or add a wiki page.

**Comment by confile** [comment]
I did not get it to work. The MetaBroadcaster does not run with PoolableBroadcasterFactory for me.

**Comment by kensiprell** [comment]
I'm going to be traveling the next couple of days. I'll take a look as soon as I have time.

Have you tried Grails 3 and the spring-websocket-plugin? That's the route I'm planning to take for all future realtime projects.

**Comment by kensiprell** [comment]
I'm not going to have time to follow up on this.
